INSERT INTO `tareas`(`id`, `nombre`, `descripcion`, `fecha_compromiso`, `prioridad`, `responsable`, `estado`,`hora_culminacion`) VALUES 
('8', 'Reunión de proyecto', 'Preparar agenda y documentos para la reunión del proyecto X', '2023-11-15', 'Alta', 'Juan Pérez', 'Pendiente','7:45'),
('9', 'Informe de ventas', 'Generar informe mensual de ventas y presentarlo al equipo de ventas', '2023-11-10', 'Media', 'María Gómez', 'En progreso','9:00'),
('10', 'Entrenamiento del personal', 'Realizar sesión de entrenamiento para el personal nuevo', '2023-11-20', 'Baja', 'Luis Rodríguez', 'Completada','12:15'),
('11', 'Desarrollo de software', 'Programar nuevas funcionalidades para la aplicación cliente', '2023-12-01', 'Alta', 'Ana Martínez', 'Pendiente','8:20'),
('12', 'Revisión de contratos', 'Revisar y actualizar los contratos con los proveedores', '2023-11-25', 'Media', 'Carlos Sánchez', 'En progreso','10:00'),
('13', 'Mantenimiento del sitio web', 'Realizar tareas de mantenimiento y actualización del sitio web de la empresa', '2023-12-05', 'Baja', 'Elena López', 'Completada','11:00'),
('14', 'Planificación de eventos', 'Planificar y coordinar eventos de la empresa para el próximo trimestre', '2023-12-10', 'Alta', 'Pedro González', 'Pendiente','6:00'),
('15', 'Informe de gastos', 'Generar informe trimestral de gastos y presentarlo a la dirección', '2023-12-15', 'Media', 'Sofía Ramírez', 'En progreso','15:15'),
('16', 'Reclutamiento de personal', 'Entrevistar candidatos para los puestos vacantes', '2023-12-20', 'Baja', 'Javier Hernández', 'Pendiente','13:45'),
('17', 'Reunión de equipo', 'Realizar reunión semanal del equipo para revisar avances y metas', '2023-12-30', 'Alta', 'Isabel Torres', 'Completada','15:35'),
('18', 'Capacitación en seguridad', 'Brindar capacitación en seguridad en el lugar de trabajo', '2024-01-05', 'Media', 'Raúl Díaz', 'En progreso','12:00'),
('19', 'Informe de calidad', 'Preparar informe de calidad de productos para la dirección', '2024-01-10', 'Baja', 'Carmen Fernández', 'Pendiente','18:00'),
('20', 'Lanzamiento de producto', 'Preparar el lanzamiento del nuevo producto en el mercado', '2024-01-15', 'Alta', 'Miguel Rodríguez', 'Pendiente','21:15'),
('21', 'Revisión de marketing', 'Revisar y optimizar estrategias de marketing digital', '2024-01-20', 'Media', 'Laura López', 'En progreso','17:00'),
('22', 'Auditoría interna', 'Realizar auditoría interna para asegurar el cumplimiento de normativas', '2024-01-25', 'Baja', 'Diego Martínez', 'Pendiente','14:20');